user: openproject
group: openproject
targets:
  centos-6:
before_precompile: "packaging/setup"
#after_install: "packaging/debian/postinst"
addons:
  - mysql
  - apache2
  - svn-dav
  - smtp
crons:
  - packaging/cron/openproject-clear-old-sessions
  - packaging/cron/openproject-create-svn-repositories

