user: openproject
group: openproject
targets:
  debian-7:
    build_dependencies:
      - libmagickwand-dev
      - libsqlite3-dev
    dependencies:
      - memcached
before_precompile: "./packaging/debian/setup.sh"
after_install: "packaging/debian/postinst"
addons:
  - mysql
  - apache2
  - smtp
