user: openproject
group: openproject
targets:
  debian-7:
    dependencies:
      - memcached
before_precompile: "./packaging/debian/setup.sh"
after_install: "packaging/debian/postinst"
buildpack: https://github.com/ddollar/heroku-buildpack-multi.git
addons:
  - mysql
  - apache2
  - smtp
