user: openproject
group: openproject
before_precompile: "./packaging/debian/setup.sh"
after_install: "packaging/debian/postinstall.sh"
buildpack: https://github.com/ddollar/heroku-buildpack-multi.git
