#!/bin/sh

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

CLI="openproject"

case "$1" in

  configure)
    rake_commands="db:migrate"
    if [ "$2" = "" ]; then
      rake_commands="${rake_commands} db:seed"
    fi

    # create attachments_path
    ${CLI} run mkdir -p /var/db/openproject/files

    # set SECRET_TOKEN env variable
    secret_token=$(< /dev/urandom tr -dc a-z0-9 | head -c128;echo;)
    ${CLI} config:get SECRET_TOKEN || ${CLI} config:set SECRET_TOKEN="$secret_token" || true

    # migrate
    ${CLI} run rake ${rake_commands} || true

    # scale
    ${CLI} scale web=1 worker=1 || true

    # let the admin reboot when he's ready
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

